services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    depends_on:
      - redis
    restart: always
    ports:
      - "8081:8080"
    environment:
      - AUTHENTICATION_API_KEY=apikey321
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://aldmiro:Passagem.92@postgres:5432/chatbotwhatsapp
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=true
      - CACHE_LOCAL_ENABLED=false
      - QR_CODE_TERMINAL=true
      - CONFIG_SESSION_PHONE_CLIENT=true
      - SERVER_PORT=8080
      - QRCODE_COLOR=#175197
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  postgres:
    image: postgres:17.6-alpine3.22
    restart: always
    environment:
      - POSTGRES_USER=aldmiro
      - POSTGRES_PASSWORD=Passagem.92
      - POSTGRES_DB=chatbotwhatsapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - evolution-net

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:

networks:
  evolution-net:
    driver: bridge
